# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'SwiftLint-Basics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftLint-Basics
  pod 'SwiftLint'

  target 'SwiftLint-BasicsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftLint-BasicsUITests' do
    # Pods for testing
  end

end
